services:
  - type: web
    name: csir_npl_ntp_data_visualization_and_monitoring
    env: python
    plan: free
    rootDir: "/opt/render/project/src/my_project" # Ensure this points to the correct directory
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn CSIR_NPL.asgi:application --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "CSIR_NPL.settings"
      - key: DEBUG
        value: "False"
      # Add other environment variables as needed
