services:
  - type: web
    name: csir-npl-django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: uvicorn CSIR_NPL.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: <your-database-url>
      - key: DJANGO_SECRET_KEY
        value: "django-insecure--n0$aj!k-@u7+p6$#2wwol&kdgr=^4@+p8&qsbr-a_p^=l9%12"
      - key: DJANGO_DEBUG
        value: false
      - key: REACT_APP_API_URL
        value: "https://csir-npl-django-backend.onrender.com"
    plan: starter
    autoDeploy: true

  - type: web
    name: csir-npl-react-frontend
    env: node
    buildCommand: npm run build
    startCommand: serve -s build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://csir-npl-django-backend.onrender.com"
    plan: starter
    autoDeploy: true
